config/routes.rb
Rails.application.routes.draw do
root to: 'gossips#index'
  resources :gossips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

    def new
        @gossip = Gossip.new
    end
    def create
        @gossip = Gossip.create(gossip_params) # create fait un new et prend un parametre en compte.
        redirect_to gossip_path(@gossip.id)
    end
    def show
        @gossip = Gossip.find(params[:id])
    end

    def edit
      @gossip = Gossip.find(params[:id])
    end

    def update
         @gossip = Gossip.find(params[:id])
      if @gossip.update(gossip_params)
        redirect_to @gossip
      else
      render 'edit'
      end
    end
def destroy
  @gossip= Gossip.find(params[:id])
  @gossip.destroy
  redirect_to gossips_path

end
    def index
      @gossips = Gossip.all
    end

    private
    def gossip_params
        params.require(:gossip).permit(:anonymous_author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<h1>Edit article</h1>
<%= form_with(model: @gossip, local: true) do |form| %>
  <% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @gossip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :anonymous_author %><br>
    <%= form.text_field :anonymous_author%>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Détruire', @gossip, method: :delete %>
<br>
<%= link_to 'Index Gossip', gossips_path %>

app/views/gossips/index.html.erb
<h1>Listing Gossips</h1>
<%= link_to 'New gossip', new_gossip_path %>
<table>
 <tr>
   <th>From</th>
   <th>Gossip</th>
   <th colspan="3"></th>
 </tr>
 <% @gossips.each do |gossip| %>
   <tr>
     <td><%= gossip.anonymous_author %></td>
     <td><%= gossip.content %></td>
     <td><%= link_to 'Show', gossip_path(gossip) %></td>
     <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
     <td><%= link_to 'Destroy', gossip_path(gossip),
             method: :delete,
             data: { confirm: 'Are you sure?' } %></td>
   </tr>
 <% end %>
</table>

app/views/gossips/new.html.erb
<h1>Gossips Thp</h1>
<p>test 1</p>

<%= form_for @gossip, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
 <%= label_tag 'anonymous_author', "Auteur "%>
  <%= f.text_field :anonymous_author %>
 <%= label_tag 'content', "Ton texte "%>
  <%= f.text_area :content %>
  <%= f.submit "Create" %>
<% end %>
<%= link_to 'Index Gossip', gossips_path %>

app/views/gossips/show.html.erb
<h1>Gossip #<%= @gossip.id %></h1

<strong> Author: </strong><%= @gossip.anonymous_author%><br />

<strong> Content: </strong><%= @gossip.content %><br /><br />

<%= link_to 'Edit this gossip', edit_gossip_path %><br />

<%= link_to 'Index Gossip', gossips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>